=== emillon/bulletml/bulletml.dtd
<!-- Generated by Relaxer 0.13 -->
<!-- Sun Jun 03 09:44:38 JST 2001 -->

<!ELEMENT vertical (#PCDATA)>
<!ATTLIST vertical type (absolute|relative|sequence) "absolute">

<!ELEMENT fireRef (param*)>
<!ATTLIST fireRef label CDATA #REQUIRED>

<!ELEMENT changeDirection (direction, term)>

<!ELEMENT bulletml (bullet | fire | action)*>
<!ATTLIST bulletml xmlns CDATA #IMPLIED>
<!ATTLIST bulletml type (none|vertical|horizontal) "none">

<!ELEMENT param (#PCDATA)>

<!ELEMENT actionRef (param*)>
<!ATTLIST actionRef label CDATA #REQUIRED>

<!ELEMENT repeat (times, (action | actionRef))>

<!ELEMENT accel (horizontal?, vertical?, term)>

<!ELEMENT times (#PCDATA)>

<!ELEMENT term (#PCDATA)>

<!ELEMENT wait (#PCDATA)>

<!ELEMENT action (changeDirection | accel | vanish | changeSpeed | repeat | wait | (fire | fireRef) | (action | actionRef))*>
<!ATTLIST action label CDATA #IMPLIED>

<!ELEMENT vanish (#PCDATA)>

<!ELEMENT speed (#PCDATA)>
<!ATTLIST speed type (absolute|relative|sequence) "absolute">

<!ELEMENT horizontal (#PCDATA)>
<!ATTLIST horizontal type (absolute|relative|sequence) "absolute">

<!ELEMENT bullet (direction?, speed?, (action | actionRef)*)>
<!ATTLIST bullet label CDATA #IMPLIED>

<!ELEMENT direction (#PCDATA)>
<!ATTLIST direction type (aim|absolute|relative|sequence) "aim">

<!ELEMENT changeSpeed (speed, term)>

<!ELEMENT fire (direction?, speed?, (bullet | bulletRef))>
<!ATTLIST fire label CDATA #IMPLIED>

<!ELEMENT bulletRef (param*)>
<!ATTLIST bulletRef label CDATA #REQUIRED>

=== emillon/bulletml/examples/[Progear]_round_3_boss_wave_bullets.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="horizontal"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
<repeat><times>10</times>
<action>
 <fire>
  <direction type="absolute">310</direction>
  <bulletRef label="wave">
   <param>-3</param>
  </bulletRef>
 </fire>
 <wait>30</wait>
 <fire>
  <direction type="absolute">230</direction>
  <bulletRef label="wave">
   <param>3</param>
  </bulletRef>
 </fire>
 <wait>30</wait>
</action>
</repeat>
<wait>60</wait>
</action>

<bullet label="wave">
<speed>1.5</speed>
<action>
<fire>
 <direction>0</direction>
 <bulletRef label="nrm"/>
</fire>
<repeat><times>12+$rank*12</times>
<action>
 <fire>
  <direction type="sequence">$1</direction>
  <bulletRef label="nrm"/>
 </fire>
 <wait>3</wait>
</action>
</repeat>
<vanish/>
</action>
</bullet>

<bullet label="nrm">
<speed>1</speed>
</bullet>

</bulletml>

=== emillon/bulletml/examples/[Original]_progear_cheap_fake.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml 
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<fire label="weekHoming">
 <direction type="aim">0</direction>
 <speed>0.1</speed>

 <bullet> <action>
  <repeat> <times>3</times> <action>
   <changeSpeed>
    <speed>1.5</speed>
    <term>30</term>
   </changeSpeed>

   <wait>30</wait>

   <repeat> <times>2+$rank*4</times> <action>
    <fire>
     <direction type="relative">90</direction>
     <speed>1.3</speed>
     <bullet/>
    </fire>
    <fire>
     <direction type="relative">-90</direction>
     <speed>1.3</speed>
     <bullet/>
    </fire>
    <wait>2</wait>
   </action> </repeat>

   <changeDirection>
    <direction type="aim">60-120*$rand</direction>
    <term>20</term>
   </changeDirection>
   <changeSpeed>
    <speed>0.1</speed>
    <term>20</term>
   </changeSpeed>
   <wait>20</wait>

  </action> </repeat>

  <changeSpeed>
   <speed>1.5</speed>
   <term>30</term>
  </changeSpeed>
  <wait>30</wait>

 </action> </bullet>
</fire>

<action label="top">
 <repeat> <times>10</times> <action>
  <fireRef label="weekHoming"/>
  <wait>60-$rank*30</wait>
 </action> </repeat>
 <wait>180</wait>
</action>

</bulletml>

=== emillon/bulletml/examples/[MDA]_circular.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
 <repeat>
  <times>$rank*10</times>
  <action>
   <fireRef label="seed">
    <param>90</param>
    <param>2</param>
    <param>355</param>
   </fireRef>
   <fireRef label="seed">
    <param>270</param>
    <param>358</param>
    <param>5</param>
   </fireRef>
   <fireRef label="aimbl"/>
   <wait>20</wait>
  </action>
 </repeat>
 <repeat>
  <times>9</times>
  <action>
   <fireRef label="aimbl"/>
   <wait>20</wait>
  </action>
 </repeat>
</action>

<fire label="seed">
 <direction type="absolute">$1</direction>
 <speed>2.8</speed>
 <bulletRef label="roll">
  <param>$2</param>
  <param>$3</param>
 </bulletRef>
</fire>

<bullet label="roll">
 <action>
  <changeDirection>
   <direction type="sequence">$1</direction>
   <term>9999</term>
  </changeDirection>
  <actionRef label="shoot"><param>$2</param></actionRef>
  <vanish/>
 </action>
</bullet>

<action label="shoot">
<repeat>
 <times>22</times>
 <action>
  <fire>
   <direction type="sequence">$1</direction>
   <speed>1.4</speed>
   <bullet/>
  </fire>
  <wait>4+$rand*8</wait>
 </action>
 </repeat>
</action>

<fire label="aimbl">
 <direction type="aim">0</direction>
 <speed>2.8</speed>
 <bullet/>
</fire>



</bulletml>

=== emillon/bulletml/examples/[ESP_RADE]_round_123_boss_izuna_fan.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">
<bulletml type="vertical" xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">
	<bullet  label="Red">
		<action/>
	</bullet>
	<bullet  label="Dummy">
		<action>
			<vanish/>
		</action>
	</bullet>
	<action  label="Stop">
		<changeSpeed>
			<speed>
				 0
			</speed>
			<term>
				 1
			</term>
		</changeSpeed>
	</action>
	<action  label="XWay">
		<actionRef  label="XWayFan">
			<param>
				 $1
			</param>
			<param>
				 $2
			</param>
			<param>
				 0
			</param>
		</actionRef>
	</action>
	<action  label="XWayFan">
		<repeat>
			<times>
				 $1-1
			</times>
			<action>
				<fire>
					<direction  type="sequence">
						$2
					</direction>
					<speed  type="sequence">
						$3
					</speed>
					<bullet/>
				</fire>
			</action>
		</repeat>
	</action>
	<action  label="fan">
		<wait>
			 2
		</wait>
		<changeSpeed>
			<speed>
				 100000
			</speed>
			<term>
				 1
			</term>
		</changeSpeed>
		<wait>
			 1-$1
		</wait>
		<actionRef  label="Stop"/>
		<fire>
			<direction  type="absolute">
				180-$3-$1*$5
			</direction>
			<speed>
				 $2
			</speed>
			<bullet/>
		</fire>
		<actionRef  label="XWay">
			<param>
				 $1
			</param>
			<param>
				 $4
			</param>
		</actionRef>
		<actionRef  label="fan">
			<param>
				 $1-1
			</param>
			<param>
				 $2+0.1
			</param>
			<param>
				 $3
			</param>
			<param>
				 $4
			</param>
			<param>
				 $5
			</param>
		</actionRef>
	</action>
	<action  label="top">
		<actionRef  label="fanMain">
			<param>
				 11+$rank*6
			</param>
			<param>
				 1
			</param>
			<param>
				 30
			</param>
			<param>
				 12-$rank*4
			</param>
			<param>
				 2.5-$rank
			</param>
		</actionRef>
		<actionRef  label="fanMain">
			<param>
				 11+$rank*6
			</param>
			<param>
				 1
			</param>
			<param>
				 -20
			</param>
			<param>
				 -12+$rank*4
			</param>
			<param>
				 -2.5+$rank
			</param>
		</actionRef>
		<actionRef  label="fanMain">
			<param>
				 13+$rank*8
			</param>
			<param>
				 1
			</param>
			<param>
				 30
			</param>
			<param>
				 12-$rank*4
			</param>
			<param>
				 2.3-$rank
			</param>
		</actionRef>
		<actionRef  label="fanMain">
			<param>
				 13+$rank*8
			</param>
			<param>
				 1
			</param>
			<param>
				 -20
			</param>
			<param>
				 -12+$rank*4
			</param>
			<param>
				 -2.3+$rank
			</param>
		</actionRef>
	</action>
	<action  label="fanMain">
		<fire>
			<direction  type="aim">
				180
			</direction>
			<speed>
				 0
			</speed>
			<bullet>
				<action>
					<actionRef  label="fan">
						<param>
							 $1
						</param>
						<param>
							 $2
						</param>
						<param>
							 $3
						</param>
						<param>
							 $4
						</param>
						<param>
							 $5
						</param>
					</actionRef>
				</action>
			</bullet>
		</fire>
		<wait>
			 90
		</wait>
	</action>
</bulletml>

=== emillon/bulletml/examples/[Bulletsmorph]_aba_1.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
  <repeat><times>5</times><action>
    <fire>
      <direction type="absolute">360 * $rand</direction>
      <bulletRef label="add2way"/>
    </fire>
    <repeat><times>71</times><action>
      <fire>
        <direction type="sequence">5</direction>
        <bulletRef label="add2way"/>
      </fire>
    </action></repeat>

  <wait>30 - 20 * $rank</wait>

  </action></repeat>

  <wait>100</wait>

</action>


<bullet label="add2way">
<speed>2.4 * (0.25 + 0.75 * $rank)</speed>
<action>

  <wait>(24 + 6 * $rand)/ (2.4 * (0.25 + 0.75 * $rank))</wait>

  <fire>
    <direction type="relative">17</direction>
    <speed type="relative">0</speed>
    <bullet/>
  </fire>
  <fire>
    <direction type="relative">-17</direction>
    <speed type="relative">0</speed>
    <bullet/>
  </fire>

</action>
</bullet>

</bulletml>

=== emillon/bulletml/examples/[Dodonpachi]_hibachi.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml 
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="allWay">
 <fire>
  <direction>-50+$rand*20</direction>
  <speed>1+$rank</speed>
  <bullet/>
 </fire>
 <repeat> <times>15+16*$rank*$rank</times>
  <action>
   <fire>
    <direction type="sequence">24-$rank*12</direction>
    <speed type="sequence">0</speed>
	<bullet/>
   </fire>
  </action>
 </repeat>
</action>

<action label="right">
 <changeDirection>
  <direction type="absolute">90</direction>
  <term>1</term>
 </changeDirection>
 <changeSpeed>
  <speed type="absolute">1</speed>
  <term>1</term>
 </changeSpeed>
 <repeat> <times>25</times>
  <action>
   <actionRef label="allWay"/>
   <wait>3</wait>
  </action>
 </repeat>

</action>

<action label="left">
 <changeDirection>
  <direction type="absolute">-90</direction>
  <term>1</term>
 </changeDirection>
 <changeSpeed>

  <speed type="absolute">1</speed>
  <term>1</term>
 </changeSpeed>
 <repeat> <times>25</times>
  <action>
   <actionRef label="allWay"/>
   <wait>3</wait>
  </action>
 </repeat>

</action>

<action label="top">
 <repeat> <times>2</times> <action>
  <actionRef label="right"/>
  <actionRef label="left"/>
  <actionRef label="left"/>
  <actionRef label="right"/>
 </action> </repeat>

 <changeSpeed>
  <speed>0</speed>
  <term>1</term>
 </changeSpeed>
 <wait>1</wait>
</action>

</bulletml>

=== emillon/bulletml/examples/[Original]_optic_seeker.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">

  <repeat><times>2 + 8 * $rank</times><action>
    <fire>
      <direction type="aim">-30 + 60 * $rand</direction>
      <speed>3.0 + 2.0 * $rank</speed>
      <bulletRef label="seal"/>
    </fire>

    <wait>25 - 20 * $rank</wait>

    <repeat><times>3</times><action>
      <fire>
        <direction type="aim">-60 + 120 * $rand</direction>
        <speed>3.0 + 2.0 * $rank</speed>
        <bulletRef label="reflect"/>
      </fire>
      <wait>25 - 20 * $rank</wait>
    </action></repeat>
  </action></repeat>

  <wait>100</wait>

</action>

<bullet label="reflect">
<action>

  <wait>(30 + 20 * $rand) * (1.0 - 0.5 * $rank)</wait>

  <repeat><times>3</times><action>
    <changeDirection>
      <direction type="relative">60 + 240 * $rand</direction>
      <term>1</term>
    </changeDirection>
    <wait>(10 + 10 * $rand) * (1.0 - 0.5 * $rank)</wait>
  </action></repeat>

  <changeDirection>
    <direction type="aim">0</direction>
    <term>1</term>
  </changeDirection>

</action>
</bullet>

<bullet label="seal">
<action>

  <wait>10 + 10 * $rand</wait>
  <changeSpeed>
    <speed>0</speed>
    <term>1</term>
  </changeSpeed>
  <wait>5</wait>

  <fire>
    <direction type="aim">0</direction>
    <speed>3.0 + 2.0 * $rank</speed>
    <bullet/>
  </fire>
  <wait>5</wait>

  <repeat><times>7</times><action>
    <fire>
      <direction type="sequence">45</direction>
      <speed>3.0 + 2.0 * $rank</speed>
      <bullet/>
    </fire>
    <wait>5</wait>
  </action></repeat>

  <fire>
    <direction type="aim">0</direction>
    <speed>3.0 + 2.0 * $rank</speed>
    <bullet/>
  </fire>

  <vanish/>

</action>
</bullet>

</bulletml>

=== emillon/bulletml/examples/[Daiouzyou]_round_3_boss.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
 <fire>
  <direction type="absolute">155</direction>
  <speed>3.3</speed>
  <bulletRef label="roll">
   <param>1</param>
  </bulletRef>
 </fire>
 <fire>
  <direction type="absolute">205</direction>
  <speed>3.3</speed>
  <bulletRef label="roll">
   <param>-1</param>
  </bulletRef>
 </fire>
 <fire>
  <direction type="absolute">135</direction>
  <speed>3.2</speed>
  <bulletRef label="roll">
   <param>1</param>
  </bulletRef>
 </fire>
 <fire>
  <direction type="absolute">225</direction>
  <speed>3.2</speed>
  <bulletRef label="roll">
   <param>-1</param>
  </bulletRef>
 </fire>
 <fire>
  <direction type="absolute">135</direction>
  <speed>2</speed>
  <bulletRef label="roll">
   <param>1</param>
  </bulletRef>
 </fire>
 <fire>
  <direction type="absolute">225</direction>
  <speed>2</speed>
  <bulletRef label="roll">
   <param>-1</param>
  </bulletRef>
 </fire>

 <wait>400</wait>
</action>

<bullet label="roll">

<action>
 <wait>12</wait>
 <changeSpeed>
  <speed>0</speed>
  <term>1</term>
 </changeSpeed>

 <fire>
  <direction type="absolute">180+90*$1</direction>
  <bullet> <action> <vanish/> </action> </bullet>
 </fire>

 <repeat> <times>200</times> <action>
  <fire>
   <direction type="sequence">9</direction>
   <speed>1+$rank</speed>
   <bullet/>
  </fire>
  <wait>2</wait>
 </action> </repeat>

 <vanish/>

</action> </bullet>

</bulletml>
