=== emillon/bulletml/bulletml.dtd
<!-- Generated by Relaxer 0.13 -->
<!-- Sun Jun 03 09:44:38 JST 2001 -->

<!ELEMENT vertical (#PCDATA)>
<!ATTLIST vertical type (absolute|relative|sequence) "absolute">

<!ELEMENT fireRef (param*)>
<!ATTLIST fireRef label CDATA #REQUIRED>

<!ELEMENT changeDirection (direction, term)>

<!ELEMENT bulletml (bullet | fire | action)*>
<!ATTLIST bulletml xmlns CDATA #IMPLIED>
<!ATTLIST bulletml type (none|vertical|horizontal) "none">

<!ELEMENT param (#PCDATA)>

<!ELEMENT actionRef (param*)>
<!ATTLIST actionRef label CDATA #REQUIRED>

<!ELEMENT repeat (times, (action | actionRef))>

<!ELEMENT accel (horizontal?, vertical?, term)>

<!ELEMENT times (#PCDATA)>

<!ELEMENT term (#PCDATA)>

<!ELEMENT wait (#PCDATA)>

<!ELEMENT action (changeDirection | accel | vanish | changeSpeed | repeat | wait | (fire | fireRef) | (action | actionRef))*>
<!ATTLIST action label CDATA #IMPLIED>

<!ELEMENT vanish (#PCDATA)>

<!ELEMENT speed (#PCDATA)>
<!ATTLIST speed type (absolute|relative|sequence) "absolute">

<!ELEMENT horizontal (#PCDATA)>
<!ATTLIST horizontal type (absolute|relative|sequence) "absolute">

<!ELEMENT bullet (direction?, speed?, (action | actionRef)*)>
<!ATTLIST bullet label CDATA #IMPLIED>

<!ELEMENT direction (#PCDATA)>
<!ATTLIST direction type (aim|absolute|relative|sequence) "aim">

<!ELEMENT changeSpeed (speed, term)>

<!ELEMENT fire (direction?, speed?, (bullet | bulletRef))>
<!ATTLIST fire label CDATA #IMPLIED>

<!ELEMENT bulletRef (param*)>
<!ATTLIST bulletRef label CDATA #REQUIRED>

=== emillon/bulletml/examples/[Original]_btb_1.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">

 <repeat> <times>2</times> <action>
  <fire>
   <bulletRef label="nway">
    <param>(8 + 28 * $rank * $rank)</param>
    <param>0.4</param>
    <param>0</param>
   </bulletRef>
  </fire>
  <wait>20</wait>

  <fire>
   <bulletRef label="nway">
    <param>(8 + 28 * $rank * $rank)</param>
    <param>0.4</param>
    <param>(360 / (8 + 28 * $rank * $rank)) * (3/4)</param>
   </bulletRef>
  </fire>
  <wait>20</wait>

  <fire>
   <bulletRef label="nway">
    <param>(8 + 28 * $rank * $rank)</param>
    <param>0.4</param>
    <param>(360 / (8 + 28 * $rank * $rank)) * (1/2)</param>
   </bulletRef>
  </fire>
  <wait>20</wait>

  <fire>
   <bulletRef label="nway">
    <param>(8 + 28 * $rank * $rank)</param>
    <param>0.4</param>
    <param>(360 / (8 + 28 * $rank * $rank)) * (3/4)</param>
   </bulletRef>
  </fire>
  <wait>20</wait>

  <fire>
   <bulletRef label="nway">
    <param>(8 + 28 * $rank * $rank)</param>
    <param>0.4</param>
    <param>(360 / (8 + 28 * $rank * $rank))</param>
   </bulletRef>
  </fire>
  <wait>20</wait>

  <fire>
   <bulletRef label="nway">
    <param>(8 + 28 * $rank * $rank)</param>
    <param>0.4</param>
    <param>(360 / (8 + 28 * $rank * $rank)) * (1/4)</param>
   </bulletRef>
  </fire>
  <wait>20</wait>

  <fire>
   <bulletRef label="nway">
    <param>(8 + 28 * $rank * $rank)</param>
    <param>0.4</param>
    <param>(360 / (8 + 28 * $rank * $rank)) * (1/2)</param>
   </bulletRef>
  </fire>
  <wait>20</wait>

  <fire>
   <bulletRef label="nway">
    <param>(8 + 28 * $rank * $rank)</param>
    <param>0.4</param>
    <param>(360 / (8 + 28 * $rank * $rank)) * (1/4)</param>
   </bulletRef>
  </fire>
  <wait>20</wait>

 </action></repeat>

 <wait>80</wait>

 <repeat> <times>10</times> <action>

  <fire>
   <bulletRef label="nwayaim">
    <param>(8 + 28 * $rank * $rank)</param>
    <param>0.8 + 0.6 * $rank</param>
    <param>(360 / (8 + 28 * $rank * $rank)) / 2</param>
   </bulletRef>
  </fire>
  <fire>
   <bulletRef label="nwayaim">
    <param>(8 + 28 * $rank * $rank)</param>
    <param>1.0 + 0.6 * $rank</param>
    <param>(360 / (8 + 28 * $rank * $rank)) / 4</param>
   </bulletRef>
  </fire>
  <fire>
   <bulletRef label="nwayaim">
    <param>(8 + 28 * $rank * $rank)</param>
    <param>1.2 + 0.6 * $rank</param>
    <param>0</param>
   </bulletRef>
  </fire>
  <wait>30</wait>

 </action></repeat>

 <wait>60</wait>

</action>

<bullet label="nway">
<direction type="absolute">0</direction>
<speed>0</speed>
<action>

 <fire>
  <direction type="absolute">$3</direction>
  <speed>$2</speed>
  <bullet/>
 </fire>

 <repeat> <times>$1</times> <action>
  <fire>
   <direction type="sequence">360 / $1</direction>
   <speed>$2</speed>
   <bullet/>
  </fire>
 </action></repeat>

 <vanish/>

</action></bullet>

<bullet label="nwayaim">
<direction type="absolute">0</direction>
<speed>0</speed>
<action>

 <fire>
  <direction type="aim">$3</direction>
  <speed>$2</speed>
  <bullet/>
 </fire>

 <repeat> <times>$1</times> <action>
  <fire>
   <direction type="sequence">360 / $1</direction>
   <speed>$2</speed>
   <bullet/>
  </fire>
 </action></repeat>

 <vanish/>

</action></bullet>

</bulletml>

=== emillon/bulletml/examples/[tenmado]_5_boss_3.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">
<action label="top">

 <fire>
  <direction type="absolute">0</direction>
  <speed>0</speed>
  <bulletRef label="stardust"/>
 </fire>

 <wait>120</wait>

 <repeat> <times>840/(120 - 100 * $rank)</times> <action>
  <fire>
   <direction type="aim">0</direction>
   <speed>1</speed>
   <bulletRef label="laser">
    <param>2</param>
   </bulletRef>
  </fire>
  <fire>
   <direction type="aim">0</direction>
   <speed>1</speed>
   <bulletRef label="laser">
    <param>2.05</param>
   </bulletRef>
  </fire>
  <fire>
   <direction type="aim">0</direction>
   <speed>1</speed>
   <bulletRef label="laser">
    <param>2.1</param>
   </bulletRef>
  </fire>
 <wait>0.5 * (120 - 100 * $rank)</wait>
 </action> </repeat>

 <wait>60</wait>
</action>

<bullet label="stardust">
<action>
 <repeat> <times>5+$rank*10</times> <action>
  <fire>
   <direction type="absolute">135 + 90 * $rand</direction>
   <speed>0.3 + 1.7 * $rand</speed>
   <bulletRef label="stardust2">
    <param>60</param>
    <param>1.2</param>
    <param>0.8</param>
   </bulletRef>
  </fire>

  <fire>
   <direction type="absolute">135 + 90 * $rand</direction>
   <speed>0.3 + 1.7 * $rand</speed>
   <bulletRef label="stardust2">
    <param>68</param>
    <param>0.8</param>
    <param>1.2</param>
   </bulletRef>
  </fire>

  <fire>
   <direction type="absolute">135 + 90 * $rand</direction>
   <speed>0.3 + 1.7 * $rand</speed>
   <bulletRef label="stardust2">
    <param>76</param>
    <param>1.2</param>
    <param>0.8</param>
   </bulletRef>
  </fire>

  <fire>
   <direction type="absolute">135 + 90 * $rand</direction>
   <speed>0.3 + 1.7 * $rand</speed>
   <bulletRef label="stardust2">
    <param>84</param>
    <param>0.8</param>
    <param>1.2</param>
   </bulletRef>
  </fire>
  <wait>960/(10+$rank*20)</wait>
 </action> </repeat>
 <vanish/>

</action> </bullet>

<bullet label="stardust2">

<action>
 <wait>$1</wait>
 <fire>
  <direction type="absolute">0</direction>
  <speed>$2</speed>
  <bullet/>
 </fire>

 <fire>
  <direction type="absolute">30</direction>
  <speed>$3</speed>
  <bullet/>
 </fire>

 <fire>
  <direction type="absolute">60</direction>
  <speed>$2</speed>
  <bullet/>
 </fire>

 <fire>
  <direction type="absolute">90</direction>
  <speed>$3</speed>
  <bullet/>
 </fire>

 <fire>
  <direction type="absolute">120</direction>
  <speed>$2</speed>
  <bullet/>
 </fire>

 <fire>
  <direction type="absolute">150</direction>
  <speed>$3</speed>
  <bullet/>
 </fire>

 <fire>
  <direction type="absolute">180</direction>
  <speed>$2</speed>
  <bullet/>
 </fire>

 <fire>
  <direction type="absolute">210</direction>
  <speed>$3</speed>
  <bullet/>
 </fire>

 <fire>
  <direction type="absolute">240</direction>
  <speed>$2</speed>
  <bullet/>
 </fire>

 <fire>
  <direction type="absolute">270</direction>
  <speed>$3</speed>
  <bullet/>
 </fire>

 <fire>
  <direction type="absolute">300</direction>
  <speed>$2</speed>
  <bullet/>
 </fire>

 <fire>
  <direction type="absolute">330</direction>
  <speed>$3</speed>
  <bullet/>
 </fire>

 <vanish/>
</action> </bullet>

<bullet label="laser">

<action>
 <changeSpeed>
  <speed>$1</speed>
  <term>1</term>
 </changeSpeed>

</action> </bullet>

</bulletml>

=== emillon/bulletml/examples/[Original]_sakuretudan.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml 
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
 <repeat> <times>10</times>
 <action>

  <fire>
   <direction>$rand*360</direction>
   <speed>2</speed>
   <bullet>
    <action>

     <changeDirection>
      <direction>0</direction>
      <term>60</term>
     </changeDirection>

     <wait>60</wait>

     <repeat> <times>15+$rank*20</times>
     <action>

     <repeat> <times>2</times>
     <action>

      <fire>
       <direction>360*$rand</direction>
       <speed>5</speed>
       <bullet>
        <action>
	 <wait>$rand*5</wait>
	 <fire>
	  <speed>$rand*4+0.5</speed>
	  <bullet/>
	 </fire>
	 <vanish/>
	</action>
       </bullet>
      </fire>

     </action>
     </repeat>

     <wait>1</wait>

     </action>
     </repeat>

     <vanish/>

    </action>
   </bullet>
  </fire>

 <wait>60</wait>

 </action>
 </repeat>

 <wait>100</wait>

</action>

</bulletml>

=== emillon/bulletml/examples/[Daiouzyou]_round_4_boss.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
 <fire>
  <direction type="absolute">110</direction>
  <speed>3</speed>
  <bulletRef label="armSrc">
   <param>1</param>
  </bulletRef>
 </fire>
 <fire>
  <direction type="absolute">-110</direction>
  <speed>3</speed>
  <bulletRef label="armSrc">
   <param>0</param>
  </bulletRef>
 </fire>

 <wait>400</wait>
</action>

<bullet label="armSrc"> <action>
 <wait>12</wait>
 <fire>
  <direction type="absolute">180</direction>
  <speed>1</speed>
  <bulletRef label="arm">
   <param>$1</param>
   <param>1</param>
  </bulletRef>
 </fire>
 <fire>
  <direction type="absolute">60</direction>
  <speed>1</speed>
  <bulletRef label="arm">
   <param>$1</param>
   <param>1</param>
  </bulletRef>
 </fire>
 <fire>
  <direction type="absolute">-60</direction>
  <speed>1</speed>
  <bulletRef label="arm">
   <param>$1</param>
   <param>1</param>
  </bulletRef>
 </fire>
 <fire>
  <direction type="absolute">180</direction>
  <speed>1</speed>
  <bulletRef label="arm">
   <param>$1</param>
   <param>-1</param>
  </bulletRef>
 </fire>
 <fire>
  <direction type="absolute">60</direction>
  <speed>1</speed>
  <bulletRef label="arm">
   <param>$1</param>
   <param>-1</param>
  </bulletRef>
 </fire>
 <fire>
  <direction type="absolute">-60</direction>
  <speed>1</speed>
  <bulletRef label="arm">
   <param>$1</param>
   <param>-1</param>
  </bulletRef>
 </fire>
 <vanish/>
</action> </bullet>

<bullet label="arm">

<action>
 <wait>12</wait>

 <fire>
  <direction type="relative">180*$1</direction>
  <bullet> <action> <vanish/> </action> </bullet>
 </fire>

 <changeSpeed>
  <speed>0</speed>
  <term>1</term>
 </changeSpeed>

 <repeat> <times>400/(6-$rank*2)</times> <action>
  <wait>6-$rank*2+$rand</wait>
  <fire>
   <direction type="sequence">11*$2</direction>
   <speed>1.5+$rank*0.5</speed>
   <bullet/>
  </fire>
 </action> </repeat>

 <vanish/>


</action> </bullet>

</bulletml>

=== emillon/bulletml/examples/[MDA]_wind_cl.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
 <fireRef label="side">
  <param>120</param>
 </fireRef>
 <fireRef label="side">
  <param>240</param>
 </fireRef>
 <wait>31</wait>
 <repeat>
  <times>5+$rank*20</times>
  <action>
   <fire>
    <bulletRef label="center"/>
   </fire>
   <wait>30</wait>
  </action>
 </repeat>
 <wait>100</wait>
</action>

<fire label="side">
 <direction type="absolute">$1</direction>
 <speed>18.6</speed>
 <bullet>
  <action>
   <wait>1</wait>
   <changeSpeed>
    <speed>0.02</speed>
    <term>2</term>
   </changeSpeed>
  <wait>30</wait>
  <changeDirection> 
   <direction>0</direction>
   <term>1</term>
  </changeDirection> 
   <repeat>
    <times>77+$rank*306</times>
    <action>
     <wait>2</wait>
     <changeDirection> 
      <direction>0</direction>
      <term>30</term>
     </changeDirection> 
     <fireRef label="3way">
      <param>0</param>
     </fireRef>
     <fireRef label="3way">
      <param>20</param>
     </fireRef>
     <fireRef label="3way">
      <param>-20</param>
     </fireRef>
    </action>
   </repeat>
  <vanish/>
  </action>
 </bullet>
</fire>

<fire label="3way">
 <direction type="relative">$1</direction>
 <speed>4.9</speed>
 <bullet/>
</fire>

<action label="2way">
 <fire>
  <direction type="relative">$1</direction>
  <speed>2.3</speed>
  <bulletRef label="dummy"/>
 </fire>
 <fire>
  <direction type="relative">-$1</direction>
  <speed>2.3</speed>
  <bulletRef label="dummy"/>
 </fire>
 <wait>5</wait>
</action>

<bullet label="dummy">
 <action/>
</bullet>

<bullet label="center">
 <action>
  <changeSpeed>
   <speed>0.01</speed>
   <term>1</term>
  </changeSpeed>
  <actionRef label="2way"><param>0</param></actionRef>
  <actionRef label="2way"><param>8-$rank*4</param></actionRef>
  <actionRef label="2way"><param>16-$rank*8</param></actionRef>
  <vanish/>
 </action>
</bullet>



</bulletml>

=== emillon/bulletml/examples/[OtakuTwo]_self-2020.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">
<bulletml type="vertical" xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
 <changeDirection>
  <direction type="absolute">0</direction>
  <term>1</term>
 </changeDirection>
 <wait>1</wait>
 <changeSpeed>
  <speed>5</speed>
  <term>1</term>
 </changeSpeed>
 <wait>15</wait>
 <changeSpeed>
  <speed>0</speed>
  <term>1</term>
 </changeSpeed>
 <repeat><times>45</times>
  <action>
   <fireRef label="seed"><param> 1</param></fireRef>
   <fireRef label="seed"><param>-1</param></fireRef>
   <wait>30</wait>
  </action>
 </repeat>
 <wait>450</wait>
</action>

<fire label="seed">
 <direction type="absolute">90*$1</direction>
 <speed>(1.5-$rank*0.5)</speed>
 <bullet>
  <action>
   <wait>$rand*(30-$rank*15)</wait>
   <repeat><times>9999</times>
    <action>
     <fire>
      <direction type="absolute">180</direction>
      <speed>1</speed>
      <bulletRef label="bomb"/>
     </fire>
     <wait>30-$rank*15</wait>
    </action>
   </repeat>
  </action>
 </bullet>
</fire>

<bullet label="bomb">
 <action>
  <wait>225</wait>
  <fire>
   <direction type="aim">-20+($rand-0.5)*$rank*$rank*$rank*$rank*$rank*$rank*$rank*$rank*20</direction>
   <speed>1.5+$rank*$rank</speed>
   <bullet/>
  </fire>
  <repeat><times>2</times>
   <action>
    <fire>
     <direction type="sequence">20</direction>
     <speed>1.5+$rank*$rank</speed>
     <bullet/>
    </fire>
   </action>
  </repeat>
 </action>
</bullet>

</bulletml>

=== emillon/bulletml/examples/[ESP_RADE]_round_5_boss_gara_5.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml 
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="accel">
 <changeDirection>
  <direction>360*$rand</direction>
  <term>1</term>
 </changeDirection>
 <changeSpeed>
  <speed>0.5+$rand*0.5</speed>
  <term>1</term>
 </changeSpeed>
</action>

<action label="stop">
 <changeSpeed>
  <speed>0</speed>
  <term>1</term>
 </changeSpeed>
</action>

<action label="stopAndWait">
 <actionRef label="stop"/>
 <wait>70-$rank*50</wait>
</action>

<action label="ippon">
 <repeat> <times>26</times>
 <action>
  <fire>
   <direction type="sequence">0</direction>
   <speed type="sequence">0.12</speed>
   <bullet/>
  </fire>
 </action>
 </repeat>
</action>

<action label="murasaki">
 <fire>
  <direction type="absolute">$2</direction>
  <speed>0.8</speed>
  <bullet/>
 </fire> 

 <repeat> <times>3+$rand*17</times>
 <action>

  <actionRef label="ippon"/>

  <wait>6</wait>

  <fire>
   <direction type="sequence">$1</direction>
   <speed>0.8</speed>
   <bullet/>
  </fire>

 </action>
 </repeat>
</action>

<action label="ao">
 <repeat> <times>3+$rand*17</times>
 <action>

  <fire>
   <speed>0.8</speed>
   <bullet/>
  </fire>

  <actionRef label="ippon"/>

  <wait>6</wait>

 </action>
 </repeat>
</action>

<action label="gara5">
 <repeat> <times>2</times>
  <action>
   <actionRef label="accel"/>

   <actionRef label="murasaki">
    <param>5</param>
    <param>180-$rand*90</param>
   </actionRef>

   <actionRef label="stopAndWait"/>
   <actionRef label="accel"/>

   <actionRef label="ao"/>

   <actionRef label="stopAndWait"/>
   <actionRef label="accel"/>

   <actionRef label="murasaki">
    <param>-5</param>
    <param>180+$rand*90</param>
   </actionRef>

   <actionRef label="stopAndWait"/>
   <actionRef label="accel"/>

   <actionRef label="ao"/>

   <actionRef label="stopAndWait"/>

  </action>
 </repeat>
</action>

<action label="top">
 <actionRef label="gara5"/>
</action>

</bulletml>

=== emillon/bulletml/examples/[Progear]_round_4_boss_fast_rocket.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="horizontal"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="fireRoot">
<fire>
 <direction type="absolute">$1</direction>
 <speed>0.2</speed>
 <bulletRef label="rootBl"/>
</fire>
<repeat> <times>3</times>
<action>
<fire>
 <direction type="absolute">$1</direction>
 <speed type="sequence">0.5</speed>
 <bulletRef label="rootBl"/>
</fire>
</action>
</repeat>
</action>

<action label="top">
<actionRef label="fireRoot">
 <param>$rand*16</param>
</actionRef>
<actionRef label="fireRoot">
 <param>180+$rand*16</param>
</actionRef>
<wait>120</wait>
</action>

<bullet label="rootBl">
<action>
<wait>40</wait>
<fire>
 <direction type="absolute">274+$rand*4</direction>
 <bulletRef label="rocket"/>
</fire>
<vanish/>
</action>
</bullet>

<bullet label="rocket">
<speed>5+$rand</speed>
<action>
<repeat> <times>9999</times>
 <action>
 <fire>
  <direction type="absolute">0</direction>
  <speed>1</speed>
  <bulletRef label="downAccel"/>
 </fire>
 <fire>
  <direction type="absolute">60</direction>
  <speed>1.8</speed>
  <bulletRef label="downAccel"/>
 </fire>
 <wait>5-$rank*4</wait>
</action>
</repeat>
</action>
</bullet>

<bullet label="downAccel">
<action>
<accel>
<vertical>2.7</vertical>
<term>120</term>
</accel>
</action>
</bullet>

</bulletml>
