=== emillon/bulletml/bulletml.dtd
<!-- Generated by Relaxer 0.13 -->
<!-- Sun Jun 03 09:44:38 JST 2001 -->

<!ELEMENT vertical (#PCDATA)>
<!ATTLIST vertical type (absolute|relative|sequence) "absolute">

<!ELEMENT fireRef (param*)>
<!ATTLIST fireRef label CDATA #REQUIRED>

<!ELEMENT changeDirection (direction, term)>

<!ELEMENT bulletml (bullet | fire | action)*>
<!ATTLIST bulletml xmlns CDATA #IMPLIED>
<!ATTLIST bulletml type (none|vertical|horizontal) "none">

<!ELEMENT param (#PCDATA)>

<!ELEMENT actionRef (param*)>
<!ATTLIST actionRef label CDATA #REQUIRED>

<!ELEMENT repeat (times, (action | actionRef))>

<!ELEMENT accel (horizontal?, vertical?, term)>

<!ELEMENT times (#PCDATA)>

<!ELEMENT term (#PCDATA)>

<!ELEMENT wait (#PCDATA)>

<!ELEMENT action (changeDirection | accel | vanish | changeSpeed | repeat | wait | (fire | fireRef) | (action | actionRef))*>
<!ATTLIST action label CDATA #IMPLIED>

<!ELEMENT vanish (#PCDATA)>

<!ELEMENT speed (#PCDATA)>
<!ATTLIST speed type (absolute|relative|sequence) "absolute">

<!ELEMENT horizontal (#PCDATA)>
<!ATTLIST horizontal type (absolute|relative|sequence) "absolute">

<!ELEMENT bullet (direction?, speed?, (action | actionRef)*)>
<!ATTLIST bullet label CDATA #IMPLIED>

<!ELEMENT direction (#PCDATA)>
<!ATTLIST direction type (aim|absolute|relative|sequence) "aim">

<!ELEMENT changeSpeed (speed, term)>

<!ELEMENT fire (direction?, speed?, (bullet | bulletRef))>
<!ATTLIST fire label CDATA #IMPLIED>

<!ELEMENT bulletRef (param*)>
<!ATTLIST bulletRef label CDATA #REQUIRED>

=== emillon/bulletml/examples/[Daiouzyou]_round_6_boss_3.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
 <repeat> <times>3</times> <action>

 <fire>
  <direction type="absolute">270</direction>
  <bulletRef label="bm_seed">
   <param>-25</param>
  </bulletRef>
 </fire>
 <wait>20</wait>
 <fire>
  <direction type="absolute">90</direction>
  <bulletRef label="bm_seed">
   <param>25</param>
  </bulletRef>
 </fire>
 <wait>100</wait>

 </action> </repeat>

</action>

<bullet label="bm_seed">
<speed>24</speed>
<action>
 <wait>1</wait>
 <fire>
  <bullet>
   <direction type="absolute">180</direction>
   <speed>3</speed>
   <actionRef label="bm"/>
  </bullet>
 </fire>
 <fire>
  <bullet>
   <direction type="sequence">$1</direction>
   <speed>2</speed>
   <actionRef label="bm"/>
  </bullet>
 </fire>
 <vanish/>
</action>
</bullet>

<action label="bm">
 <changeSpeed>
  <speed>0</speed>
  <term>50</term>
 </changeSpeed>
 <wait>45</wait>
 <fire>
  <bulletRef label="round">
   <param>1.5</param>
   <param>0</param>
  </bulletRef>
 </fire>
 <fire>
  <bulletRef label="round">
   <param>1.25</param>
   <param>7</param>
  </bulletRef>
 </fire>
 <fire>
  <bulletRef label="round">
   <param>1</param>
   <param>14</param>
  </bulletRef>
 </fire>
 <vanish/>
</action>
 
<bullet label="round">
<speed>0</speed>
<action>
 <fire>
  <direction type="absolute">$2</direction>
  <speed>$1</speed>
  <bullet/>
 </fire>
 <repeat> <times>10+$rank*10</times>
 <action>
  <fire>
   <direction type="sequence">360/(10+$rank*10)</direction>
   <speed>$1</speed>
   <bullet/>
  </fire>
 </action>
 </repeat>
 <vanish/>
</action>
</bullet>

</bulletml>

=== emillon/bulletml/examples/[Original]_fujin_ranbu_true.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">

 <fire>
  <bulletRef label="dummy">
   <param>0.6 + 0.6 * $rank</param>
   <param>48 - 41 * $rank</param>
   <param>8 * $rank</param>
  </bulletRef>
 </fire>

 <wait>400 - 100 * $rank</wait>

</action>

<bullet label="dummy">
<direction type="absolute">0</direction>
<speed>0</speed>
<action>
 <changeDirection>
  <direction type="absolute">180</direction>
  <term>1</term>
 </changeDirection>
 <changeSpeed>
  <speed>2</speed>
  <term>20</term>
 </changeSpeed>

 <repeat> <times>3</times><action>
  <fire>
   <direction type="absolute">180 + 60</direction>
   <bulletRef label="bit">
    <param>$1</param>
    <param>$2</param>
    <param>-$3</param>
   </bulletRef>
  </fire>

  <wait>10</wait>

  <fire>
   <direction type="absolute">180 - 60</direction>
   <bulletRef label="bit">
    <param>$1</param>
    <param>$2</param>
    <param>$3</param>
   </bulletRef>
  </fire>

  <wait>10</wait>
 </action></repeat>

 <changeSpeed>
  <speed>0</speed>
  <term>20</term>
 </changeSpeed>

 <repeat> <times>1</times><action>
  <fire>
   <direction type="absolute">180 + 60</direction>
   <bulletRef label="bit">
    <param>$1</param>
    <param>$2</param>
    <param>-$3</param>
   </bulletRef>
  </fire>

  <wait>10</wait>

  <fire>
   <direction type="absolute">180 - 60</direction>
   <bulletRef label="bit">
    <param>$1</param>
    <param>$2</param>
    <param>$3</param>
   </bulletRef>
  </fire>

  <wait>10</wait>
 </action></repeat>

 <changeDirection>
  <direction type="absolute">0</direction>
  <term>1</term>
 </changeDirection>
 <changeSpeed>
  <speed>2</speed>
  <term>30</term>
 </changeSpeed>

 <repeat> <times>999</times><action>
  <fire>
   <direction type="absolute">180 + 60</direction>
   <bulletRef label="bit">
    <param>$1</param>
    <param>$2</param>
    <param>-$3</param>
   </bulletRef>
  </fire>

  <wait>10</wait>

  <fire>
   <direction type="absolute">180 - 60</direction>
   <bulletRef label="bit">
    <param>$1</param>
    <param>$2</param>
    <param>$3</param>
   </bulletRef>
  </fire>

  <wait>10</wait>
 </action></repeat>

 <vanish/>

</action></bullet>

<bullet label="bit"><action>

 <fire>
  <direction type="aim">0</direction>
  <bulletRef label="shotgun">
   <param>$1</param>
  </bulletRef>
 </fire>

 <wait>$2</wait>

 <repeat> <times>200</times><action>
  <fire>
   <direction type="sequence">$3</direction>
   <bulletRef label="shotgun">
    <param>$1</param>
   </bulletRef>
  </fire>

  <wait>$2</wait>

 </action></repeat>

 <vanish/>

</action></bullet>

<bullet label="shotgun">
<speed>0.001</speed>
<action>

 <fire>
  <direction type="relative">0</direction>
  <speed>$1</speed>
  <bullet/>
 </fire>
 <fire>
  <direction type="relative">0</direction>
  <speed>$1 * 1.1</speed>
  <bullet/>
 </fire>
 <fire>
  <direction type="relative">0</direction>
  <speed>$1 * 1.21</speed>
  <bullet/>
 </fire>
 <fire>
  <direction type="relative">0</direction>
  <speed>$1 * 1.331</speed>
  <bullet/>
 </fire>
 <fire>
  <direction type="relative">0</direction>
  <speed>$1 * 1.4641</speed>
  <bullet/>
 </fire>
 <fire>
  <direction type="relative">0</direction>
  <speed>$1 * 1.610510</speed>
  <bullet/>
 </fire>
 <vanish/>

</action></bullet>

</bulletml>

=== emillon/bulletml/examples/[Noiz2sa]_88way.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
 <fire>
  <direction type="absolute">180</direction>
  <speed>0.7</speed>
  <bullet>
   <actionRef label="main"/>
  </bullet>
 </fire>
 <wait>200</wait>
</action>

<action label="main">
 <repeat> <times>6+$rank*10</times>
 <action>
  <fire>
   <direction type="sequence">360/(6+$rank*10)</direction>
   <bulletRef label="16way"/>
  </fire>
  <wait>100/(6+$rank*10)</wait>
 </action>
 </repeat>
 <vanish/>
</action>

<bullet label="16way">
<speed>$rand+1</speed>
<action>
 <wait>20+$rand*40</wait>
 <repeat> <times>16</times>
 <action>
  <fire>
   <direction type="sequence">22.5</direction>
   <bullet>
    <speed>1.7</speed>
   </bullet>
  </fire>
 </action>
 </repeat>
 <vanish/>
 </action>
</bullet>

</bulletml>

=== emillon/bulletml/examples/[MDA]_acc_n_dec.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
	<repeat>
		<times>5+(20*$rank)</times>
		<action>
			<fireRef label="seed"><param>90</param></fireRef>
			<fireRef label="seed"><param>270</param></fireRef>
			<wait>55-($rank*30)</wait>
		</action>
	</repeat>
</action>

<fire label="seed">
	<direction type="absolute">$1</direction>
	<speed>2.0</speed>
	<bullet>
		<action>
			<changeSpeed>
				<speed>0</speed>
				<term>20</term>
			</changeSpeed>
			<wait>20</wait>
				<actionRef label="way"/>
			<vanish/>
		</action>
	</bullet>
</fire>

<action label="way">
	<fire>
		<direction type="aim">$rand*60-30-70</direction>
		<speed>4.2</speed>
		<bulletRef label="br"/>
	</fire>
	<repeat>
		<times>7</times>
		<action>
			<fire>
				<direction type="sequence">8.5</direction>
				<speed>1.05</speed>
				<bulletRef label="ac"/>
			</fire>
			<fire>
				<direction type="sequence">8.5</direction>
				<speed>4.2</speed>
				<bulletRef label="br"/>
			</fire>
		</action>
	</repeat>
</action>

<bullet label="br">
	<action>
		<changeSpeed>
			<speed>1.05</speed>
			<term>25</term>
		</changeSpeed>
	</action>
</bullet>

<bullet label="ac">
	<action>
		<changeSpeed>
			<speed>8.4</speed>
			<term>150</term>
		</changeSpeed>
		<wait>9999</wait>
		<fire><bullet/></fire>
	</action>
</bullet>

</bulletml>

=== emillon/bulletml/examples/[Original]_gurutyo.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml 
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<fire label="gurutyo">
 <direction type="absolute">90</direction>
 <speed>$1*(3+$rank*4)</speed>

 <bullet>
 <action>

 <changeDirection>
  <direction type="sequence">$1*6</direction>
  <term>1000</term>
 </changeDirection>

 <repeat> <times>500</times>
 <action>

  <fire>
   <direction type="relative">0</direction>
   <bullet/>
  </fire>

  <wait>1</wait>

 </action>
 </repeat>

 <vanish/>

 </action>
 </bullet>
</fire>

<action label="top">
 <fireRef label="gurutyo">
  <param>1</param>
 </fireRef>
 <fireRef label="gurutyo">
  <param>-1</param>
 </fireRef>

 <wait>550</wait>

</action>

</bulletml>

=== emillon/bulletml/examples/[Daiouzyou]_round_6_boss_1.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
 <repeat> <times>64</times>
 <action>
  <wait>2</wait>
  <actionRef label="four">
   <param>$rand*90+135</param>
  </actionRef>
 </action>
 </repeat>
</action>

<action label="four">
 <fire>
  <direction type="absolute">90</direction>
  <speed>6</speed>
  <bulletRef label="rb">
   <param>$1</param>
  </bulletRef>
 </fire>
 <repeat> <times>3</times>
 <action>
  <fire>
   <direction type="sequence">60</direction>
   <speed>6</speed>
   <bulletRef label="rb">
    <param>$1</param>
   </bulletRef>
  </fire>
 </action>
 </repeat>
</action>

<bullet label="rb">
 <actionRef label="red">
  <param>$1+$rand*20-10</param>
 </actionRef>
</bullet>

<action label="red">
 <wait>1</wait>
 <fire>
  <direction type="absolute">$1</direction>
  <speed>1.2+$rank</speed>
  <bullet/>
 </fire>
 <vanish/>
</action>

</bulletml>

=== emillon/bulletml/examples/[XEVIOUS]_garu_zakato.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="vertical"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
<repeat> <times>10</times>
<action>

<fire>
 <direction type="absolute">180</direction>
 <speed>3</speed>
 <bulletRef label="gzc"/>
</fire>

<wait>20-$rank*10+$rand*10</wait>

</action>
</repeat>

<wait>60</wait>
</action>

<bullet label="gzc">
<action>
<wait>10+$rand*10</wait>
<repeat><times>16</times>
<action>
 <fire>
  <direction type="sequence">360/16</direction>
  <bulletRef label="spr"/>
 </fire>
</action>
</repeat>
<repeat><times>4</times>
<action>
 <fire>
  <direction type="sequence">90</direction>
  <bulletRef label="hrmSpr"/>
 </fire>
</action>
</repeat>
<vanish/>
</action>
</bullet>

<bullet label="spr">
<speed>2</speed>
</bullet>

<bullet label="hrmSpr">
<speed>0</speed>
<action>
<changeSpeed>
 <speed>2</speed>
 <term>60</term>
</changeSpeed>
</action>
<action>
<repeat><times>9999</times>
<action>
 <changeDirection>
  <direction type="aim">0</direction>
  <term>40</term>
 </changeDirection>
 <wait>1</wait>
</action>
</repeat>
</action>
</bullet>

</bulletml>

=== emillon/bulletml/examples/[Progear]_round_5_middle_boss_rockets.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "../bulletml.dtd">

<bulletml type="horizontal"
          xmlns="http://www.asahi-net.or.jp/~cs8k-cyu/bulletml">

<action label="top">
<repeat><times>50</times>
<action>
 <fire>
  <direction type="absolute">270</direction>
  <bulletRef label="rocket"/>
 </fire>
 <wait>10</wait>
</action>
</repeat>
<wait>120</wait>
</action>

<bullet label="rocket">
<action>
<repeat><times>9999</times>
<action>
 <fireRef label="udBlt">
  <param>90</param>
 </fireRef>
 <wait>20-$rank*8</wait>
 <fireRef label="udBlt">
  <param>-90</param>
 </fireRef>
 <wait>$rand*10+15-$rank*8</wait>
</action>
</repeat>
</action>
</bullet>

<fire label="udBlt">
<direction type="relative">$1-25+$rand*50</direction>
<bullet/>
</fire>

</bulletml>
